### ISSUE TITLE
Update Project Discussion

### ISSUE THREAD

**Issue by arnoheigvd** [arnoheigvd/DAI_labo1_Schildbock_Tribolet#14]
Add to this [discussion](https://github.com/orgs/heig-vd-dai-course/discussions/352) the link of the repo and the final commit

**Comment by arnoheigvd** [comment]
Following the evaluation criteria "The GitHub Discussion is updated with the link to the repository and a related commit hash before the deadline - every 24 hours after the deadline will result in a -1 point penalty on the final grade"

**Comment by shadowkudo** [comment]
before adding the repo to the discussion, we will need to merge the branch develop (when running/documented smoothly) to the main/master

**Comment by arnoheigvd** [comment]
Final version merged to main

**Comment by arnoheigvd** [comment]
[Discussion](https://github.com/orgs/heig-vd-dai-course/discussions/352) updated and issue solved !

**Comment by shadowkudo** [comment]
[Tag](https://github.com/arnoheigvd/DAI_labo1_Schildbock_Tribolet/releases/tag/rendu) created
