### ISSUE TITLE
Edit README

### ISSUE THREAD

**Issue by arnoheigvd** [arnoheigvd/DAI_labo1_Schildbock_Tribolet#16]
Need to adress evaluation requirements:
9. The README is well structured and explains the purpose of your application so new users can understand it
10. The README explains how to use your application with examples and outputs so a new user/developer can understand your application without having to run it locally
11. The README describes explicit commands to clone and build your application with Git and Maven so new developers can start and develop your project on their own computer

**Comment by shadowkudo** [comment]
closing issue

**Comment by shadowkudo** [comment]
need to reopen to fix a few things

**Comment by shadowkudo** [comment]
this time it is really finished -> closing
