### ISSUE TITLE
Presentation

### ISSUE THREAD

**Issue by shadowkudo** [arnoheigvd/DAI_labo1_Schildbock_Tribolet#27]
@arnoheigvd, you need to check it and tell me which silde you want to talk (50/50 for 5 minutes talking time without question(1 min for them))

**Comment by shadowkudo** [comment]
branch presentation contains my last push

**Comment by shadowkudo** [comment]
added pictures and fix some mistakes -> commit - [983dbdc](https://github.com/arnoheigvd/DAI_labo1_Schildbock_Tribolet/commit/983dbdc46d3b610ac35aed4d85872160c5ece33d)

**Comment by arnoheigvd** [comment]
I guess we should talk about the algorithm we implemented. I'm not sure it's possible to make a minute on the slide Plan/Introduction, do you have any idea? For the slides themself, they are fine for me

**Comment by arnoheigvd** [comment]
As discussed by phone:
- Intro @shadowkudo  ~30s
- Workflow @arnoheigvd ~1m
- CLI App @shadowkudo ~1m
- Cesar @shadowkudo ~1m
- AES @arnoheigvd  ~1m
- Outro @arnoheigvd ~30s
