### ISSUE TITLE
implement the first algorithm/mode

### ISSUE THREAD

**Issue by shadowkudo** [arnoheigvd/DAI_labo1_Schildbock_Tribolet#3]
create the first mode to encrypt/decrypt using the code Cesar

**Comment by shadowkudo** [comment]
there is a need of some comment and better print to the terminal

**Comment by shadowkudo** [comment]
> there is a need of some comment and better print to the terminal

it is done in this [commit](https://github.com/arnoheigvd/DAI_labo1_Schildbock_Tribolet/commit/ad1853c5dc9016c4e9c9b661dc009b478c618d87)

**Comment by arnoheigvd** [comment]
Closed

**Comment by shadowkudo** [comment]
created issue #18 to solve the bug
