### ISSUE TITLE
Review the code according to the evaluation criteria

### ISSUE THREAD

**Issue by shadowkudo** [arnoheigvd/DAI_labo1_Schildbock_Tribolet#8]
[evaluation criteria](https://github.com/heig-vd-dai-course/heig-vd-dai-course/blob/main/07-practical-work-1/COURSE_MATERIAL.md#grading-criteria)

**Comment by arnoheigvd** [comment]
# Review Category 1 : Meta

1. The whole team contributes to the project and can explain it in details to share knowledge between the team  
We both contributed to the project, @shadowkudo implementing the app structure and the code cesar and @arnoheigvd by implementing the AES-ECB algorithm
2. A GitHub Discussion is opened during the first week of the project to explain the idea of the project so the teachers can validate the idea  
The [discussion](https://github.com/orgs/heig-vd-dai-course/discussions/352) was open in time and validate by the teacher  
3. The GitHub Discussion is updated with the link to the repository and a related commit hash before the deadline - every 24 hours after the deadline will result in a -1 point penalty on the final grade
Create related issue #14

**Comment by shadowkudo** [comment]
closing issue
